# TODO: switch to rust-toolchain action
# TODO: use cache action

name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C debuginfo=0"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Formatting
        run: cargo fmt --all -- --check

      - name: Test
        run: cargo test --workspace

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Docs
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps
